### ISSUE TITLE
Problems with Django 1.6

### ISSUE THREAD

**Issue by djq** [RyanBalfanz/django-sendgrid#64]
Hi,

When installing `1.0.1` I am getting the below error. Do you know what might be going on? Thank you.

```
Traceback (most recent call last):
  File "./manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Library/Python/2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/Library/Python/2.7/site-packages/south/migration/__init__.py", line 233, in migrate_app
    migrator.load_initial_data(target, db=database)
  File "/Library/Python/2.7/site-packages/south/migration/migrators.py", line 224, in load_initial_data
    call_command('loaddata', 'initial_data', verbosity=self.verbosity, database=db)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Library/Python/2.7/site-packages/django/core/management/commands/loaddata.py", line 55, in handle
    self.loaddata(fixture_labels)
  File "/Library/Python/2.7/site-packages/django/core/management/commands/loaddata.py", line 84, in loaddata
    self.load_label(fixture_label)
  File "/Library/Python/2.7/site-packages/django/core/management/commands/loaddata.py", line 134, in load_label
    for obj in objects:
  File "/Library/Python/2.7/site-packages/django/core/serializers/json.py", line 76, in Deserializer
    six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
  File "/Library/Python/2.7/site-packages/django/core/serializers/json.py", line 70, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/Library/Python/2.7/site-packages/django/core/serializers/python.py", line 90, in Deserializer
    Model = _get_model(d["model"])
  File "/Library/Python/2.7/site-packages/django/core/serializers/python.py", line 153, in _get_model
    raise base.DeserializationError("Invalid model identifier: '%s'" % model_identifier)
django.core.serializers.base.DeserializationError: Problem installing fixture '/Library/Python/2.7/site-packages/sendgrid/fixtures/initial_data.json': Invalid model identifier: 'sendgrid.eventtype'
```

**Comment by djq** [comment]
oops, this appears to have been a problem with the version of south that I was using (`0.8.3`). See South bug here: http://south.aeracode.org/ticket/1320

**Comment by RyanBalfanz** [comment]
@djq, Glad it's working. Nonetheless, thanks for the report! :)
